name: toko_swalayan
description: Aplikasi Toko Swalayan dengan Flutter
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: 3.9.0 

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  cached_network_image: ^3.3.0
  google_fonts: ^6.1.0
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/